name: Windows Workflow Example

on: push  # Run when code is pushed

jobs:
  build:
    runs-on: windows-latest  # Use a Windows machine

    steps:
      - uses: actions/checkout@v3  # Step 1: Checkout the repository
      - name: Run a Windows command
        run: |
          echo Hello from Windows!
          dir  # List all files in the directory
